openapi: 3.0.3
info:
  version: 1.0.0
  title: Liveness

paths:
  /liveness:
    get:
      summary: Check the liveness of the API
      operationId: liveness
      tags:
        - liveness
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '../common/Liveness.yaml#/components/schemas/LivenessResponse'
        400:
          $ref: '#/components/responses/400'
        500:
          $ref: '#/components/responses/500'

components:
  responses:
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '../common/Error.yaml#/components/schemas/ErrorResponse'
    500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '../common/Error.yaml#/components/schemas/ErrorResponse'
